const allowedOrigins = [
  "http://localhost:3000",
  "http://localhost:3001",
  "https://wibxc.xyz",
  "https://wibxc.xyz/products",
  "https://wibxc.xyz/syria",
  "https://wibxc.xyz/pi",

  "http://143.42.61.215/",
  "http://143.42.61.215",
  "https://143.42.61.215",
  "https://143.42.61.215/warranty",
  "https://143.42.61.215/check",
  "https://143.42.61.215/login",
  "http://products.agsdubai.com",
  "http://143.42.61.215:5000/warranty",
  "http://products.agsdubai.com/login",
  "http://ags-sales.com",
  "http://ags-sales.com/check",
  "http://ags-sales.com/products",
  "http://hmcfz.co",
  "http://hmcfz.co/check",
  "http://hmcfz.co/products",
  "https://products.agsdubai.com/login",
  "https://ags-sales.com",
  "https://ags-sales.com/check",
  "https://ags-sales.com/products",
  "https://hmcfz.co",
  "https://hmcfz.co/check",
  "https://hmcfz.co/products",
];

export default allowedOrigins;
