export const processStatuses = [
  "STARTED",
  "APPROVED_BY_SALES_MANAGER",
  "APPROVED_BY_FINANCE",
  "STAMPED_BY_CUSTOMER",
  "DEPOSIT_PAID",
  "BOOKED",
  "FULL_PAYMENT",
  "INVOICE_READY",
  "PKL_READY",
  "DONE_DEAL",
];

export const processStatusesEnum = {
  STARTED: "STARTED",
  APPROVED_BY_SALES_MANAGER: "APPROVED_BY_SALES_MANAGER",
  APPROVED_BY_FINANCE: "APPROVED_BY_FINANCE",
  STAMPED_BY_CUSTOMER: "STAMPED_BY_CUSTOMER",
  DEPOSIT_PAID: "DEPOSIT_PAID",
  BOOKED: "BOOKED",
  FULL_PAYMENT: "FULL_PAYMENT",
  INVOICE_READY: "INVOICE_READY",
  PKL_READY: "PKL_READY",
  DONE_DEAL: "DONE_DEAL",
};
